Changing variables names

diff --git a/pipework b/pipework
--- a/pipework
+++ b/pipework
@@ -69,13 +69,13 @@ while getopts wn:R:D:h opt ; do
     esac
 done
 
-if [ -z "${NETCONF}" ]; then
+if [ -z "$NETCONF" ]; then
     usage
     echo "${err} : At least one interface must be defined"
     exit 1
 fi
 
-if [ -z "${GUESTNAME}" ]; then
+if [ -z "$GUESTNAME" ]; then
     usage
     echo "${err} : Couldn't get container id. Please check the docker command (-D)"
     exit 1
@@ -123,11 +123,11 @@ esac
 n=1
 CURRENTIF=$(ifconfig -a | sed 's/[ \t].*//;/^\(lo\|\)$/d')
 
-for int in ${NETCONF}; do
-    IFNAME=$(echo ${int} | awk -F':' '{print $1}')
-    VLANID=$(echo ${IFNAME} | awk -F'.' '{print $2}')
-    IPADDR=$(echo ${int} | awk -F':' '{print $2}')
-    CONTAINER_IFNAME=$(echo ${int} | awk -F':' '{print $3}')
+for INT in $NETCONF; do
+    IFNAME=$(echo $INT | awk -F':' '{print $1}')
+    VLANID=$(echo $IFNAME | awk -F'.' '{print $2}')
+    IPADDR=$(echo $INT | awk -F':' '{print $2}')
+    CONTAINER_IFNAME=$(echo $INT | awk -F':' '{print $3}')
 
     if [ -z ${CONTAINER_IFNAME} ]; then
         CONTAINER_IFNAME=eth${n}
@@ -167,20 +167,20 @@ else
 fi
 
     # Create vlan interface if it doesn't exist
-    if ! [ -z ${VLANID} ] && ! $(echo ${CURRENTIF} | grep -q ${IFNAME}); then
-        vconfig add ${IFNAME%.*} ${VLANID}
+    if ! [ -z $VLANID ] && ! $(echo $CURRENTIF | grep -q $IFNAME); then
+        vconfig add ${IFNAME%.*} $VLANID
         ip link set ${IFNAME%.*} up
-        ip link set ${IFNAME} up
+        ip link set $IFNAME up
         sleep 0.5
-        while ! grep -q ^1$ /sys/class/net/${IFNAME}/carrier 2>/dev/null; do
+        while ! grep -q ^1$ /sys/class/net/$IFNAME/carrier 2>/dev/null; do
             sleep 1
         done
     fi  
     
     CURRENTIF=$(ifconfig -a | sed 's/[ \t].*//;/^\(lo\|\)$/d')
 
-    if ! $(echo ${CURRENTIF} | grep -q ${IFNAME}) && ! [[ "${IFNAME}" == br* ]]; then
-        echo "${err} : Interface ${IFNAME} does not exist"
+    if ! $(echo $CURRENTIF | grep -q $IFNAME) && ! [[ "$IFNAME" == br* ]]; then
+        echo "${err} : Interface $IFNAME does not exist"
         exit 1
     fi
 
@@ -211,9 +211,9 @@ fi
 if [ $DOCKERPID ]; then
     NSPID=$DOCKERPID
 else
-    NSPID=$(sed -n ${n}p $(find "$CGROUPMNT" -name "${GUESTNAME}" | head -n 1)/tasks)
+    NSPID=$(sed -n ${n}p $(find "$CGROUPMNT" -name "$GUESTNAME" | head -n 1)/tasks)
     [ "$NSPID" ] || {
-    echo "Could not find a process inside container ${GUESTNAME}."
+    echo "Could not find a process inside container $GUESTNAME."
     exit 1
 }
     fi
@@ -301,8 +301,8 @@ if ! [[ -z "${routefile}" ]]; then
     )
 fi
 
-echo -ne "${info} : Container ${GUESTNAME} is "
-if $(docker ps -q --no-trunc | grep -q ${GUESTNAME}); then
+echo -ne "${info} : Container $GUESTNAME is "
+if $(docker ps -q --no-trunc | grep -q $GUESTNAME); then
     echo "started"
 else
     echo "stopped"
