Convert tabs to space; set tab width to 2 characters; add style guide
Supersedes #136. Thanks to @kojiromike, who did the initial pull request!

diff --git a/pipework b/pipework
--- a/pipework
+++ b/pipework
@@ -1,10 +1,12 @@
 #!/bin/sh
+# This code should (try to) follow Google's Shell Style Guide
+# (https://google-styleguide.googlecode.com/svn/trunk/shell.xml)
 set -e
 
 case "$1" in
-    --wait)
-      WAIT=1
-      ;;
+  --wait)
+    WAIT=1
+    ;;
 esac
 
 IFNAME=$1
@@ -21,19 +23,22 @@ IPADDR=$3
 MACADDR=$4
 
 case "$MACADDR" in
-    *@*)
-        VLAN="${MACADDR#*@}" VLAN="${VLAN%%@*}"
-        MACADDR="${MACADDR%%@*}"
-        ;;
-    *) VLAN=;;
+  *@*)
+    VLAN="${MACADDR#*@}"
+    VLAN="${VLAN%%@*}"
+    MACADDR="${MACADDR%%@*}"
+    ;;
+  *)
+    VLAN=
+    ;;
 esac
 
 [ "$IPADDR" ] || [ "$WAIT" ] || {
-    echo "Syntax:"
-    echo "pipework <hostinterface> [-i containerinterface] <guest> <ipaddr>/<subnet>[@default_gateway] [macaddr][@vlan]"
-    echo "pipework <hostinterface> [-i containerinterface] <guest> dhcp [macaddr][@vlan]"
-    echo "pipework --wait [-i containerinterface]"
-    exit 1
+  echo "Syntax:"
+  echo "pipework <hostinterface> [-i containerinterface] <guest> <ipaddr>/<subnet>[@default_gateway] [macaddr][@vlan]"
+  echo "pipework <hostinterface> [-i containerinterface] <guest> dhcp [macaddr][@vlan]"
+  echo "pipework --wait [-i containerinterface]"
+  exit 1
 }
 
 # Succeed if the given utility is installed. Fail otherwise.
@@ -41,49 +46,46 @@ esac
 # http://stackoverflow.com/questions/592620/check-if-a-program-exists-from-a-bash-script/677212#677212
 # (Thanks to @chenhanxiao for pointing this out!)
 installed () {
-    command -v "$1" >/dev/null 2>&1
+  command -v "$1" >/dev/null 2>&1
 }
 
-# First step: determine type of first argument (bridge, physical interface...), skip if --wait set
+# First step: determine type of first argument (bridge, physical interface...),
+# Unless "--wait" is set (then skip the whole section)
 if [ -z "$WAIT" ]; then 
-    if [ -d /sys/class/net/$IFNAME ]
-    then
-        if [ -d /sys/class/net/$IFNAME/bridge ]
-        then
-            IFTYPE=bridge
-            BRTYPE=linux
-        elif installed ovs-vsctl && ovs-vsctl list-br|grep -q ^$IFNAME$
-        then
-            IFTYPE=bridge
-            BRTYPE=openvswitch
-        elif [ $(cat /sys/class/net/$IFNAME/type) -eq 32 ]; # Infiniband IPoIB interface type 32
-        then
-            IFTYPE=ipoib
-            # The IPoIB kernel module is fussy, set device name to ib0 if not overridden
-            CONTAINER_IFNAME=${CONTAINER_IFNAME:-ib0}
-        else IFTYPE=phys
-        fi
-    else
-        case "$IFNAME" in
-        br*)
-            IFTYPE=bridge
-            BRTYPE=linux
-            ;;
-        ovs*)
-            if ! installed ovs-vsctl
-            then
-                echo "Need OVS installed on the system to create an ovs bridge"
-                exit 1
-            fi
-            IFTYPE=bridge
-            BRTYPE=openvswitch
-            ;;
-        *)
-            echo "I do not know how to setup interface $IFNAME."
-            exit 1
-            ;;
-        esac
+  if [ -d /sys/class/net/$IFNAME ]
+  then
+    if [ -d /sys/class/net/$IFNAME/bridge ]; then
+      IFTYPE=bridge
+      BRTYPE=linux
+    elif installed ovs-vsctl && ovs-vsctl list-br|grep -q ^$IFNAME$; then
+      IFTYPE=bridge
+      BRTYPE=openvswitch
+    elif [ $(cat /sys/class/net/$IFNAME/type) -eq 32 ]; then # Infiniband IPoIB interface type 32
+      IFTYPE=ipoib
+      # The IPoIB kernel module is fussy, set device name to ib0 if not overridden
+      CONTAINER_IFNAME=${CONTAINER_IFNAME:-ib0}
+    else IFTYPE=phys
     fi
+  else
+    case "$IFNAME" in
+      br*)
+        IFTYPE=bridge
+        BRTYPE=linux
+        ;;
+      ovs*)
+        if ! installed ovs-vsctl; then
+          echo "Need OVS installed on the system to create an ovs bridge"
+          exit 1
+        fi
+        IFTYPE=bridge
+        BRTYPE=openvswitch
+        ;;
+      *)
+        echo "I do not know how to setup interface $IFNAME."
+        exit 1
+        ;;
+    esac
+  fi
 fi
 
 # Set the default container interface name to eth1 if not already set
@@ -102,21 +104,20 @@ CONTAINER_IFNAME=${CONTAINER_IFNAME:-eth1}
 }
 
 [ $IFTYPE = bridge ] && [ $BRTYPE = linux ] && [ "$VLAN" ] && {
-    echo "VLAN configuration currently unsupported for Linux bridge."
-    exit 1
+  echo "VLAN configuration currently unsupported for Linux bridge."
+  exit 1
 }
 
 [ $IFTYPE = ipoib ] && [ $MACADDR ] && {
-	echo "MACADDR configuration unsupported for IPoIB interfaces."
-	exit 1
+  echo "MACADDR configuration unsupported for IPoIB interfaces."
+  exit 1
 }
 
 # Second step: find the guest (for now, we only support LXC containers)
-while read dev mnt fstype options dump fsck
-do
-    [ "$fstype" != "cgroup" ] && continue
-    echo $options | grep -qw devices || continue
-    CGROUPMNT=$mnt
+while read dev mnt fstype options dump fsck; do
+  [ "$fstype" != "cgroup" ] && continue
+  echo $options | grep -qw devices || continue
+  CGROUPMNT=$mnt
 done < /proc/mounts
 
 [ "$CGROUPMNT" ] || {
@@ -127,70 +128,70 @@ done < /proc/mounts
 # Try to find a cgroup matching exactly the provided name.
 N=$(find "$CGROUPMNT" -name "$GUESTNAME" | wc -l)
 case "$N" in
-    0)
-	# If we didn't find anything, try to lookup the container with Docker.
-	if installed docker
-	then
-        RETRIES=3
-        while [ $RETRIES -gt 0 ]; do
-      	    DOCKERPID=$(docker inspect --format='{{ .State.Pid }}' $GUESTNAME)
-            [ $DOCKERPID != 0 ] && break
-            sleep 1
-            RETRIES=$((RETRIES - 1))
-        done
+  0)
+    # If we didn't find anything, try to lookup the container with Docker.
+    if installed docker; then
+      RETRIES=3
+      while [ $RETRIES -gt 0 ]; do
+        DOCKERPID=$(docker inspect --format='{{ .State.Pid }}' $GUESTNAME)
+        [ $DOCKERPID != 0 ] && break
+        sleep 1
+        RETRIES=$((RETRIES - 1))
+      done
 
-        [ "$DOCKERPID" = 0 ] && {
-      		echo "Docker inspect returned invalid PID 0"
-    		exit 1
-      	}
+     [ "$DOCKERPID" = 0 ] && {
+       echo "Docker inspect returned invalid PID 0"
+       exit 1
+     }
 
         [ "$DOCKERPID" = "<no value>" ] && {
-      		echo "Container $GUESTNAME not found, and unknown to Docker."
-    		exit 1
-      	}
-	else
-	    echo "Container $GUESTNAME not found, and Docker not installed."
-	    exit 1
-	fi
-	;;
+          echo "Container $GUESTNAME not found, and unknown to Docker."
+        exit 1
+        }
+  else
+      echo "Container $GUESTNAME not found, and Docker not installed."
+      exit 1
+  fi
+  ;;
     1)
-	true
-	;;
+  true
+  ;;
     *)
-	echo "Found more than one container matching $GUESTNAME."
-	exit 1
-	;;
+  echo "Found more than one container matching $GUESTNAME."
+  exit 1
+  ;;
 esac
 
-if [ "$IPADDR" = "dhcp" ]
-then
-    # Check for first available dhcp client
-    DHCP_CLIENT_LIST="udhcpc dhcpcd dhclient"
-    for CLIENT in $DHCP_CLIENT_LIST; do
-        installed "$CLIENT" && {
-            DHCP_CLIENT=$CLIENT
-            break
-        }
-    done
-    [ -z $DHCP_CLIENT ] && {
-    	echo "You asked for DHCP; but no DHCP client could be found."
-    	exit 1
+if [ "$IPADDR" = "dhcp" ]; then
+  # Check for first available dhcp client
+  DHCP_CLIENT_LIST="udhcpc dhcpcd dhclient"
+  for CLIENT in $DHCP_CLIENT_LIST; do
+    installed "$CLIENT" && {
+      DHCP_CLIENT=$CLIENT
+      break
     }
+  done
+  [ -z $DHCP_CLIENT ] && {
+    echo "You asked for DHCP; but no DHCP client could be found."
+    exit 1
+  }
 else
-    # Check if a subnet mask was provided.
-    echo $IPADDR | grep -q / || {
-	echo "The IP address should include a netmask."
-	echo "Maybe you meant $IPADDR/24 ?"
-	exit 1
-    }
-    # Check if a gateway address was provided.
-    case "$IPADDR" in
-        *@*)
-            GATEWAY="${IPADDR#*@}" GATEWAY="${GATEWAY%%@*}"
-            IPADDR="${IPADDR%%@*}"
-            ;;
-        *) GATEWAY=;;
-    esac
+  # Check if a subnet mask was provided.
+  echo $IPADDR | grep -q / || {
+    echo "The IP address should include a netmask."
+    echo "Maybe you meant $IPADDR/24 ?"
+    exit 1
+  }
+  # Check if a gateway address was provided.
+  case "$IPADDR" in
+    *@*)
+      GATEWAY="${IPADDR#*@}" GATEWAY="${GATEWAY%%@*}"
+      IPADDR="${IPADDR%%@*}"
+      ;;
+    *)
+      GATEWAY=
+      ;;
+  esac
 fi
 
 if [ $DOCKERPID ]; then
@@ -198,17 +199,17 @@ if [ $DOCKERPID ]; then
 else
   NSPID=$(head -n 1 $(find "$CGROUPMNT" -name "$GUESTNAME" | head -n 1)/tasks)
   [ "$NSPID" ] || {
-      echo "Could not find a process inside container $GUESTNAME."
-      exit 1
+    echo "Could not find a process inside container $GUESTNAME."
+    exit 1
   }
 fi
 
 # Check if an incompatible VLAN device already exists
 [ $IFTYPE = phys ] && [ "$VLAN" ] && [ -d /sys/class/net/$IFNAME.VLAN ] && {
-    [ -z "$(ip -d link show $IFNAME.$VLAN | grep "vlan.*id $VLAN")" ] && {
-        echo "$IFNAME.VLAN already exists but is not a VLAN device for tag $VLAN"
-        exit 1
-    }
+  [ -z "$(ip -d link show $IFNAME.$VLAN | grep "vlan.*id $VLAN")" ] && {
+    echo "$IFNAME.VLAN already exists but is not a VLAN device for tag $VLAN"
+    exit 1
+  }
 }
 
 [ ! -d /var/run/netns ] && mkdir -p /var/run/netns
@@ -217,30 +218,30 @@ ln -s /proc/$NSPID/ns/net /var/run/netns/$NSPID
 
 # Check if we need to create a bridge.
 [ $IFTYPE = bridge ] && [ ! -d /sys/class/net/$IFNAME ] && {
-    [ $BRTYPE = linux ] && {
-        (ip link add dev $IFNAME type bridge > /dev/null 2>&1) || (brctl addbr $IFNAME)
-        ip link set $IFNAME up
-    }
-    [ $BRTYPE = openvswitch ] && {
-        ovs-vsctl add-br $IFNAME
-    }
+  [ $BRTYPE = linux ] && {
+    (ip link add dev $IFNAME type bridge > /dev/null 2>&1) || (brctl addbr $IFNAME)
+    ip link set $IFNAME up
+  }
+  [ $BRTYPE = openvswitch ] && {
+    ovs-vsctl add-br $IFNAME
+  }
 }
 
 MTU=$(ip link show $IFNAME | awk '{print $5}')
 # If it's a bridge, we need to create a veth pair
 [ $IFTYPE = bridge ] && {
-    LOCAL_IFNAME="v${CONTAINER_IFNAME}pl${NSPID}"
-    GUEST_IFNAME="v${CONTAINER_IFNAME}pg${NSPID}"
-    ip link add name $LOCAL_IFNAME mtu $MTU type veth peer name $GUEST_IFNAME mtu $MTU
-    case "$BRTYPE" in
-        linux)
-            (ip link set $LOCAL_IFNAME master $IFNAME > /dev/null 2>&1) || (brctl addif $IFNAME $LOCAL_IFNAME)
-            ;;
-        openvswitch)
-            ovs-vsctl add-port $IFNAME $LOCAL_IFNAME ${VLAN:+"tag=$VLAN"}
-            ;;
-    esac
-    ip link set $LOCAL_IFNAME up
+  LOCAL_IFNAME="v${CONTAINER_IFNAME}pl${NSPID}"
+  GUEST_IFNAME="v${CONTAINER_IFNAME}pg${NSPID}"
+  ip link add name $LOCAL_IFNAME mtu $MTU type veth peer name $GUEST_IFNAME mtu $MTU
+  case "$BRTYPE" in
+    linux)
+      (ip link set $LOCAL_IFNAME master $IFNAME > /dev/null 2>&1) || (brctl addif $IFNAME $LOCAL_IFNAME)
+      ;;
+    openvswitch)
+      ovs-vsctl add-port $IFNAME $LOCAL_IFNAME ${VLAN:+"tag=$VLAN"}
+      ;;
+  esac
+  ip link set $LOCAL_IFNAME up
 }
 
 # Note: if no container interface name was specified, pipework will default to ib0
@@ -254,17 +255,16 @@ MTU=$(ip link show $IFNAME | awk '{print $5}')
 
 # If it's a physical interface, create a macvlan subinterface
 [ $IFTYPE = phys ] && {
-    [ "$VLAN" ] && {
-        [ ! -d /sys/class/net/$IFNAME.$VLAN ] && {
-            ip link add link $IFNAME name $IFNAME.$VLAN mtu $MTU type vlan id $VLAN
-        }
-
-        ip link set $IFNAME up
-        IFNAME=$IFNAME.$VLAN
+  [ "$VLAN" ] && {
+    [ ! -d /sys/class/net/$IFNAME.$VLAN ] && {
+      ip link add link $IFNAME name $IFNAME.$VLAN mtu $MTU type vlan id $VLAN
     }
-    GUEST_IFNAME=ph$NSPID$CONTAINER_IFNAME
-    ip link add link $IFNAME dev $GUEST_IFNAME mtu $MTU type macvlan mode bridge
     ip link set $IFNAME up
+    IFNAME=$IFNAME.$VLAN
+  }
+  GUEST_IFNAME=ph$NSPID$CONTAINER_IFNAME
+  ip link add link $IFNAME dev $GUEST_IFNAME mtu $MTU type macvlan mode bridge
+  ip link set $IFNAME up
 }
 
 ip link set $GUEST_IFNAME netns $NSPID
@@ -272,37 +272,38 @@ ip netns exec $NSPID ip link set $GUEST_IFNAME name $CONTAINER_IFNAME
 [ "$MACADDR" ] && ip netns exec $NSPID ip link set dev $CONTAINER_IFNAME address $MACADDR
 if [ "$IPADDR" = "dhcp" ]
 then
-    [ $DHCP_CLIENT = "udhcpc"  ] && ip netns exec $NSPID $DHCP_CLIENT -qi $CONTAINER_IFNAME -x hostname:$GUESTNAME
-    if [ $DHCP_CLIENT = "dhclient"  ]
-    then
-        # kill dhclient after get ip address to prevent device be used after container close
-        ip netns exec $NSPID $DHCP_CLIENT -pf "/var/run/dhclient.$NSPID.pid" $CONTAINER_IFNAME
-        kill "$(cat "/var/run/dhclient.$NSPID.pid")"
-        rm "/var/run/dhclient.$NSPID.pid"
-    fi
-    [ $DHCP_CLIENT = "dhcpcd"  ] && ip netns exec $NSPID $DHCP_CLIENT -q $CONTAINER_IFNAME -h $GUESTNAME
+  [ $DHCP_CLIENT = "udhcpc"  ] && ip netns exec $NSPID $DHCP_CLIENT -qi $CONTAINER_IFNAME -x hostname:$GUESTNAME
+  if [ $DHCP_CLIENT = "dhclient"  ]; then
+    # kill dhclient after get ip address to prevent device be used after container close
+    ip netns exec $NSPID $DHCP_CLIENT -pf "/var/run/dhclient.$NSPID.pid" $CONTAINER_IFNAME
+    kill "$(cat "/var/run/dhclient.$NSPID.pid")"
+    rm "/var/run/dhclient.$NSPID.pid"
+  fi
+  [ $DHCP_CLIENT = "dhcpcd"  ] && ip netns exec $NSPID $DHCP_CLIENT -q $CONTAINER_IFNAME -h $GUESTNAME
 else
-    ip netns exec $NSPID ip addr add $IPADDR dev $CONTAINER_IFNAME
-    [ "$GATEWAY" ] && {
-	ip netns exec $NSPID ip route delete default >/dev/null 2>&1 && true
-    }
-    ip netns exec $NSPID ip link set $CONTAINER_IFNAME up
-    [ "$GATEWAY" ] && {
-	ip netns exec $NSPID ip route get $GATEWAY >/dev/null 2>&1 || \
-		ip netns exec $NSPID ip route add $GATEWAY/32 dev $CONTAINER_IFNAME
-	ip netns exec $NSPID ip route replace default via $GATEWAY
-    }
+  ip netns exec $NSPID ip addr add $IPADDR dev $CONTAINER_IFNAME
+  [ "$GATEWAY" ] && {
+    ip netns exec $NSPID ip route delete default >/dev/null 2>&1 && true
+  }
+  ip netns exec $NSPID ip link set $CONTAINER_IFNAME up
+  [ "$GATEWAY" ] && {
+    ip netns exec $NSPID ip route get $GATEWAY >/dev/null 2>&1 || \
+    ip netns exec $NSPID ip route add $GATEWAY/32 dev $CONTAINER_IFNAME
+    ip netns exec $NSPID ip route replace default via $GATEWAY
+  }
 fi
 
 # Give our ARP neighbors a nudge about the new interface
-if installed arping
-then
-    IPADDR=$(echo $IPADDR | cut -d/ -f1)
-    ip netns exec $NSPID arping -c 1 -A -I $CONTAINER_IFNAME $IPADDR > /dev/null 2>&1 || true
+if installed arping; then
+  IPADDR=$(echo $IPADDR | cut -d/ -f1)
+  ip netns exec $NSPID arping -c 1 -A -I $CONTAINER_IFNAME $IPADDR > /dev/null 2>&1 || true
 else
-    echo "Warning: arping not found; interface may not be immediately reachable"
+  echo "Warning: arping not found; interface may not be immediately reachable"
 fi
 
 # Remove NSPID to avoid `ip netns` catch it.
 [ -f /var/run/netns/$NSPID ] && rm -f /var/run/netns/$NSPID
+
 exit 0
+
+# vim: set tabstop=2 shiftwidth=2 softtabstop=2 expandtab :
