Add traffic control + basic implementation of ipip/gre tunneling that do not work as per the netns limitations (tested on 3.16 kernel)

diff --git a/pipework b/pipework
--- a/pipework
+++ b/pipework
@@ -41,7 +41,7 @@ run() {
 check_kernel_module() {
     MODULE_NAME=$1
     modinfo $MODULE_NAME >/dev/null 2>&1 || {
-        echo "Warning: module $MODULE_NAME is required to perform this action" 
+        echo "Error: module $MODULE_NAME is required to perform this action" 
         exit 1
     }
 }
@@ -97,6 +97,54 @@ set_netns_ip() {
     fi
 }
 
+# Setup an IP tunnel
+# Usage set_tunnel ipip|gre NSPID CONTAINER_IFNAME IPADDR ROUTES
+set_tunnel() {
+
+    ACTION=$1
+    NSPID=$2
+    CONTAINER_IFNAME=$3
+    IPADDR=$4
+    ROUTES=$5
+
+    # Test IPv4/IPv6 
+    if [ $(echo $IPADDR | grep -q :) ]; 
+    then
+        if [ $ACTION = ipip ]
+        then
+            TUNL_NAME=ip6tnl0
+            TUNL_MODE=ip6ip6
+        elif [ $ACTION = gre ]
+        then
+            TUNL_NAME=ip6gre0
+            TUNL_MODE=sit
+        fi
+    else 
+        if [ $ACTION = ipip ]
+        then
+            TUNL_NAME=tunl0
+            TUNL_MODE=ipip
+        elif [ $ACTION = gre ]
+        then
+            TUNL_NAME=gre0
+            TUNL_MODE=gre
+        fi
+    fi
+    run ip netns exec $NSPID ip tunnel add $TUNL_NAME mode $TUNL_MODE dev $CONTAINER_IFNAME
+    ADDRS=$(echo $IPADDR | tr ',' ' ')
+    for ADDR in $ADDRS; do 
+        run ip netns exec $NSPID ip addr add $IPADDR dev $TUNL_NAME
+    done
+
+    [ "$ROUTES" ] && {
+        ROUTES=$(echo $ROUTES | tr ',' ' ')
+        for ROUTE in $ROUTES; do
+            run ip netns exec $NSPID $IPROUTE_PREFIX route add $ROUTE via $GATEWAY dev $CONTAINER_IFNAME
+        done
+    }
+}
+
+
 ## Parse args
 if [ $# -lt 3 ]
 then
@@ -129,43 +177,47 @@ while [ $# -gt 0 ]; do
             case "$ACTION" in
                 # Collect args specific to actions
                 link)
-                ;;
+                   ;;
                 ip|sec_ip)
-                shift
-                IPADDR=$1
-                # Check if a subnet mask was provided.
-                echo $IPADDR | grep -q / || {
-                    echo "The IP address should include a netmask."
-                    echo "Maybe you meant $IPADDR/24 ?"
-                    exit 1
-                }
-                # Check if a gateway address was provided.
-                if echo $IPADDR | grep -q @
-                then
-                    GATEWAY=$(echo $IPADDR | cut -d@ -f2)
-                    IPADDR=$(echo $IPADDR | cut -d@ -f1)
-                else
-                    GATEWAY=
-                fi
-                ;;
+                    shift
+                    IPADDR=$1
+                    # Check if a subnet mask was provided.
+                    echo $IPADDR | grep -q / || {
+                        echo "The IP address should include a netmask."
+                        echo "Maybe you meant $IPADDR/24 ?"
+                        exit 1
+                    }
+                    # Check if a gateway address was provided.
+                    if echo $IPADDR | grep -q @
+                    then
+                        GATEWAY=$(echo $IPADDR | cut -d@ -f2)
+                        IPADDR=$(echo $IPADDR | cut -d@ -f1)
+                    else
+                        GATEWAY=
+                    fi
+                    ;;
+                dhcp)
+                    DHCP=1
+                    ;;
                 # This part is a little future-proof, as it seems there's many patchs to come in the kernel 
                 # See http://thread.gmane.org/gmane.linux.network/315933/focus=321753 and https://patchwork.ozlabs.org/patch/440660/ 
                 # Doing the following setup "works" but we share the tunnel in all the namespaces (useless) and we can't delete anymore the gre/gretap/tun@NONE interfaces 
                 # - https://ringzraw.wordpress.com/2014/09/14/linux-network-namespaces-and-gre/
                 ipip)
-                shift
-                IPIP_ADDR=$1
-                check_kernel_module ipip
-                check_kernel_module ip6_tunnel
-                ;;
+                    shift
+                    check_kernel_module ipip
+                    check_kernel_module ip6_tunnel
+                    IPADDR=$1
+                    ;;
                 gre)
-                GRE_REMOTE=$1
-                check_kernel_module gre
-                check_kernel_module ip6_gre
-                ;;
-                dhcp)
-                DHCP=1
-                ;;
+                    check_kernel_module gre
+                    check_kernel_module ip6_gre
+                    IPADDR=$2
+                    ;;
+                tc)
+                    shift
+                    QOS=$@
+                    ;;
             esac
             ;;
         --interface|-i)
@@ -418,25 +470,33 @@ ln -s /proc/$NSPID/ns/net /var/run/netns/$NSPID
     run ip link set $GUEST_IFNAME netns $NSPID
     run ip netns exec $NSPID ip link set $GUEST_IFNAME name $CONTAINER_IFNAME
     [ "$MACADDR" ] && run ip netns exec $NSPID ip link set dev $CONTAINER_IFNAME address $MACADDR
-
-    # If link only, we can exit here
-    [ $ACTION = link ] && exit 0
 }
 
-if [ "$ACTION" = "dhcp" ] 
-then    
-    [ $DHCP_CLIENT = "udhcpc"  ] && run ip netns exec $NSPID $DHCP_CLIENT -qi $CONTAINER_IFNAME -x hostname:$GUESTNAME
-    if [ $DHCP_CLIENT = "dhclient"  ]
-    then
-        # kill dhclient after get ip address to prevent device be used after container close
-        run ip netns exec $NSPID $DHCP_CLIENT -pf "/var/run/dhclient.$NSPID.pid" $CONTAINER_IFNAME
-        kill "$(cat "/var/run/dhclient.$NSPID.pid")"
-        rm "/var/run/dhclient.$NSPID.pid"
-    fi      
-    [ $DHCP_CLIENT = "dhcpcd"  ] && run ip netns exec $NSPID $DHCP_CLIENT -q $CONTAINER_IFNAME -h $GUESTNAME
-else    
-    set_netns_ip $NSPID $CONTAINER_IFNAME $IPADDR $GATEWAY $ROUTES
-fi          
+case "$ACTION" in
+    link) 
+        exit 0
+        ;;
+    dhcp)
+        [ $DHCP_CLIENT = "udhcpc"  ] && run ip netns exec $NSPID $DHCP_CLIENT -qi $CONTAINER_IFNAME -x hostname:$GUESTNAME
+        if [ $DHCP_CLIENT = "dhclient"  ]
+        then
+            # kill dhclient after get ip address to prevent device be used after container close
+            run ip netns exec $NSPID $DHCP_CLIENT -pf "/var/run/dhclient.$NSPID.pid" $CONTAINER_IFNAME
+            kill "$(cat "/var/run/dhclient.$NSPID.pid")"
+            rm "/var/run/dhclient.$NSPID.pid"
+        fi      
+        [ $DHCP_CLIENT = "dhcpcd"  ] && run ip netns exec $NSPID $DHCP_CLIENT -q $CONTAINER_IFNAME -h $GUESTNAME
+        ;;
+    ip|sec_ip) 
+        set_netns_ip $NSPID $CONTAINER_IFNAME $IPADDR $GATEWAY $ROUTES
+        ;;
+    ipip|gre)
+        set_tunnel $ACTION $NSPID $CONTAINER_IFNAME $IPADDR $ROUTES
+        ;;
+    tc) 
+        run ip netns exec $NSPID tc $QOS
+        ;;
+esac  
         
 # Remove NSPID to avoid `ip netns` catch it.
 [ -f /var/run/netns/$NSPID ] && rm -f /var/run/netns/$NSPID
