Report if unable to create files/links required, and suggest sudo

diff --git a/pipework b/pipework
--- a/pipework
+++ b/pipework
@@ -14,11 +14,12 @@ while (( $# )); do
             # Collect each route in another ${ROUTE[x]} entry
             shift
             ROUTE[${#ROUTE[*]}]=$1
+            (( VERB )) && echo "Route network: $1"
             ;;
         --interface|-i)
             shift
             CONTAINER_IFNAME=$1
-            (( VERB )) && echo "Guest i'face: $CONTAINER_IFNAME"
+            (( VERB )) && echo "Guest i'face:  $CONTAINER_IFNAME"
             ;;
         --*|-*) # unrecognized, eg. --help, -?
             HELP=1
@@ -27,16 +28,16 @@ while (( $# )); do
         *)
             if   [ -z "$IFNAME" ]; then
                 IFNAME=$1
-                (( VERB )) && echo "Host  i'face: $IFNAME"
+                (( VERB )) && echo "Host  i'face:  $IFNAME"
             elif [ -z "$GUESTNAME" ]; then
                 GUESTNAME=$1
-                (( VERB )) && echo "Guest name:   $GUESTNAME"
+                (( VERB )) && echo "Guest name:    $GUESTNAME"
             elif [ -z "$IPADDR" ]; then
                 IPADDR=$1
-                (( VERB )) && echo "IP  address:  $IPADDR"
+                (( VERB )) && echo "IP  address:   $IPADDR"
             elif [ -z "$MACADDR" ]; then
                 MACADDR=$1
-                (( VERB )) && echo "MAC address:  $MACADDR"
+                (( VERB )) && echo "MAC address:   $MACADDR"
             else
                 HELP=1
                 echo "Invalid argument: $1"
@@ -46,8 +47,6 @@ while (( $# )); do
     shift
 done
 
-[ "$IPADDR" ] || HELP=1
-
 [ "$WAIT" ] && {
   while ! grep -q ^1$ /sys/class/net/$CONTAINER_IFNAME/carrier 2>/dev/null
   do sleep 1
@@ -55,6 +54,7 @@ done
   exit 0
 }
 
+[ "$IPADDR" ] || HELP=1
 [ "$HELP" ] && {
     echo "Syntax:"
     echo "pipework <hostinterface> <guest> <ipaddr>/<subnet>[@default_gateway] [macaddr]"
@@ -178,11 +178,14 @@ if [ -z "$NSPID" ]; then
     echo "Could not find a process inside container $GUESTNAME."
     exit 1
 fi
+(( VERB )) && echo "Found container process PID $NSPID"
 
-mkdir -p /var/run/netns
-rm -f /var/run/netns/$NSPID
-ln -s /proc/$NSPID/ns/net /var/run/netns/$NSPID
-
+if ! mkdir -p /var/run/netns \
+    || ! rm -f /var/run/netns/$NSPID \
+    || ! ln -s /proc/$NSPID/ns/net /var/run/netns/$NSPID; then
+    echo "Could not prepare to adjust container networking; run using sudo?"
+    exit 1
+fi
 
 # Check if we need to create a bridge.
 if [ "$IFTYPE" = "bridge" ] && [ ! -d /sys/class/net/$IFNAME ]; then
