Copy "use libcontainer" pull request
Shamelessly copy https://github.com/jpetazzo/pipework/pull/41

diff --git a/pipework b/pipework
--- a/pipework
+++ b/pipework
@@ -110,41 +110,26 @@ done < /proc/mounts
 # Try to find a cgroup matching exactly the provided name.
 N=$(find "$CGROUPMNT" -name "$GUESTNAME" | wc -l)
 case "$N" in
-    0)
-	# If we didn't find anything, try to lookup the container with Docker.
-	if which docker >/dev/null
-	then
-	    DOCKERID=$(docker inspect --format='{{.ID}}' $GUESTNAME)
-	    [ "$DOCKERID" = "<no value>" ] && {
-		echo "Container $GUESTNAME not found, and unknown to Docker."
+	0)
+		# If we didn't find anything, try to lookup the container with Docker.
+		if which docker >/dev/null
+		then
+			DOCKERPID=$(docker inspect --format='{{ .State.Pid }}' $GUESTNAME)
+			[ "$DOCKERPID" = "<no value>" ] && {
+			echo "Container $GUESTNAME not found, and unknown to Docker."
+			exit 1 }
+		else
+			echo "Container $GUESTNAME not found, and Docker not installed."
+			exit 1
+		fi
+		;;
+	1)
+		true
+		;;
+	*)
+		echo "Found more than one container matching $GUESTNAME."
 		exit 1
-	    }
-	    NN=$(find "$CGROUPMNT" -name "$DOCKERID" | wc -l)
-	    case "$NN" in
-		0)
-		    echo "Container $GUESTNAME doesn't seem to be running."
-		    exit 1
-		    ;;
-		1)
-		    GUESTNAME=$DOCKERID
-		    ;;
-		*)
-		    echo "Multiple cgroup entries for container $GUESTNAME."
-		    exit 1
-		    ;;
-	    esac
-	else
-	    echo "Container $GUESTNAME not found, and Docker not installed."
-	    exit 1
-	fi
-	;;
-    1)
-	true
-	;;
-    *)
-	echo "Found more than one container matching $GUESTNAME."
-	exit 1
-	;;
+		;;
 esac
 
 if [ "$IPADDR" = "dhcp" ]
@@ -171,11 +156,15 @@ else
     fi
 fi
 
-NSPID=$(head -n 1 $(find "$CGROUPMNT" -name "$GUESTNAME" | head -n 1)/tasks)
-[ "$NSPID" ] || {
-    echo "Could not find a process inside container $GUESTNAME."
-    exit 1
+if [ $DOCKERPID ]; then
+	NSPID=$DOCKERPID
+else
+	NSPID=$(sed -n ${n}p $(find "$CGROUPMNT" -name "${GUESTNAME}" | head -n 1)/tasks)
+	[ "$NSPID" ] || {
+	echo "Could not find a process inside container ${GUESTNAME}."
+	exit 1
 }
+	fi
 
 mkdir -p /var/run/netns
 rm -f /var/run/netns/$NSPID
