Fix misplaced automatic vlan creation

diff --git a/pipework b/pipework
--- a/pipework
+++ b/pipework
@@ -144,38 +144,12 @@ for INT in $NETCONF; do
         CONTAINER_IFNAME=eth${n}
     fi
 
-[ -n "$WAIT" ] && {
-  while ! grep -q ^1$ /sys/class/net/$CONTAINER_IFNAME/carrier 2>/dev/null
-  do sleep 1
-  done
-  exit 0
-}
-
-# determine type of first argument (bridge, physical interface...)
-if [ -d /sys/class/net/$IFNAME ]
-then
-    if [ -d /sys/class/net/$IFNAME/bridge ]
-    then
-        IFTYPE=bridge
-        BRTYPE=linux
-    elif $(which ovs-vsctl >/dev/null) && $(ovs-vsctl list-br|grep -q ^$IFNAME$)
-    then
-        IFTYPE=bridge
-        BRTYPE=openvswitch
-    else IFTYPE=phys
-    fi
-else
-    case "$IFNAME" in
-    br*)
-        IFTYPE=bridge
-        BRTYPE=linux
-        ;;
-    *)
-        echo "I do not know how to setup interface $IFNAME."
-        exit 1
-        ;;
-    esac
-fi
+    [ -n "$WAIT" ] && {
+      while ! grep -q ^1$ /sys/class/net/$CONTAINER_IFNAME/carrier 2>/dev/null
+      do sleep 1
+      done
+      exit 0
+    }
 
     # Create vlan interface if it doesn't exist
     if ! [ -z $VLANID ] && ! $(echo $CURRENTIF | grep -q $IFNAME); then
@@ -188,6 +162,32 @@ fi
         done
     fi  
 
+    # determine type of first argument (bridge, physical interface...)
+    if [ -d /sys/class/net/$IFNAME ]
+    then
+        if [ -d /sys/class/net/$IFNAME/bridge ]
+        then
+            IFTYPE=bridge
+            BRTYPE=linux
+        elif $(which ovs-vsctl >/dev/null) && $(ovs-vsctl list-br|grep -q ^$IFNAME$)
+        then
+            IFTYPE=bridge
+            BRTYPE=openvswitch
+        else IFTYPE=phys
+        fi
+    else
+        case "$IFNAME" in
+        br*)
+            IFTYPE=bridge
+            BRTYPE=linux
+            ;;
+        *)
+            echo "I do not know how to setup interface $IFNAME."
+            exit 1
+            ;;
+        esac
+    fi
+
     if ! [ -z $VERBOSE ]; then
         echo -e "type: $IFTYPE\thost_interface: $IFNAME\tip_addr: $IPADDR\tcontainer_int: $CONTAINER_IFNAME\tmac_addr: $MACADDR\troute_file: $ROUTEFILE\n"
     fi  
@@ -199,108 +199,108 @@ fi
         exit 1
     fi
 
-if [ "$IPADDR" = "dhcp" ]
-then
-    # We use udhcpc to obtain the DHCP lease, make sure it's installed.
-    which udhcpc >/dev/null || {
-    echo "You asked for DHCP; please install udhcpc first."
-    exit 1
-    }
-else
-    # Check if a subnet mask was provided.
-    echo $IPADDR | grep -q / || {
-    echo "The IP address should include a netmask."
-    echo "Maybe you meant $IPADDR/24 ?"
-    exit 1
-    }
-    # Check if a gateway address was provided.
-    if echo $IPADDR | grep -q @
+    if [ "$IPADDR" = "dhcp" ]
     then
-        GATEWAY=$(echo $IPADDR | cut -d@ -f2)
-        IPADDR=$(echo $IPADDR | cut -d@ -f1)
+        # We use udhcpc to obtain the DHCP lease, make sure it's installed.
+        which udhcpc >/dev/null || {
+        echo "You asked for DHCP; please install udhcpc first."
+        exit 1
+        }
     else
-        GATEWAY=
+        # Check if a subnet mask was provided.
+        echo $IPADDR | grep -q / || {
+        echo "The IP address should include a netmask."
+        echo "Maybe you meant $IPADDR/24 ?"
+        exit 1
+        }
+        # Check if a gateway address was provided.
+        if echo $IPADDR | grep -q @
+        then
+            GATEWAY=$(echo $IPADDR | cut -d@ -f2)
+            IPADDR=$(echo $IPADDR | cut -d@ -f1)
+        else
+            GATEWAY=
+        fi
     fi
-fi
-
-if [ $DOCKERPID ]; then
-    NSPID=$DOCKERPID
-else
-    NSPID=$(sed -n ${n}p $(find "$CGROUPMNT" -name "$GUESTNAME" | head -n 1)/tasks)
-    [ "$NSPID" ] || {
-    echo "Could not find a process inside container $GUESTNAME."
-    exit 1
-}
+    
+    if [ $DOCKERPID ]; then
+        NSPID=$DOCKERPID
+    else
+        NSPID=$(sed -n ${n}p $(find "$CGROUPMNT" -name "$GUESTNAME" | head -n 1)/tasks)
+        [ "$NSPID" ] || {
+        echo "Could not find a process inside container $GUESTNAME."
+        exit 1
+    }
+        fi
+    
+    mkdir -p /var/run/netns
+    rm -f /var/run/netns/$NSPID
+    ln -s /proc/$NSPID/ns/net /var/run/netns/$NSPID
+    
+    
+    # Check if we need to create a bridge.
+    [ $IFTYPE = bridge ] && [ ! -d /sys/class/net/$IFNAME ] && {
+        (ip link set $IFNAME type bridge > /dev/null 2>&1) || (brctl addbr $IFNAME)
+        ip link set $IFNAME up
+    }
+    
+    # If it's a bridge, we need to create a veth pair
+    [ $IFTYPE = bridge ] && {
+        LOCAL_IFNAME=pl$NSPID$CONTAINER_IFNAME
+        GUEST_IFNAME=pg$NSPID$CONTAINER_IFNAME
+        ip link add name $LOCAL_IFNAME type veth peer name $GUEST_IFNAME
+        case "$BRTYPE" in
+            linux)
+                (ip link set $LOCAL_IFNAME master $IFNAME > /dev/null 2>&1) || (brctl addif $IFNAME $LOCAL_IFNAME)
+                ;;
+            openvswitch)
+                ovs-vsctl add-port $IFNAME $LOCAL_IFNAME
+                ;;
+        esac
+        ip link set $LOCAL_IFNAME up
+    }
+    
+    # If it's a physical interface, create a macvlan subinterface
+    [ $IFTYPE = phys ] && {
+        GUEST_IFNAME=ph$NSPID$CONTAINER_IFNAME
+        ip link add link $IFNAME dev $GUEST_IFNAME type macvlan mode bridge
+        ip link set $IFNAME up
+    }
+    
+    ip link set $GUEST_IFNAME netns $NSPID
+    ip netns exec $NSPID ip link set $GUEST_IFNAME name $CONTAINER_IFNAME
+    
+    # Setting macaddress
+    if ! [ -z $MACADDR ];then
+        ip netns exec $NSPID ip link set $CONTAINER_IFNAME address $MACADDR
     fi
-
-mkdir -p /var/run/netns
-rm -f /var/run/netns/$NSPID
-ln -s /proc/$NSPID/ns/net /var/run/netns/$NSPID
-
-
-# Check if we need to create a bridge.
-[ $IFTYPE = bridge ] && [ ! -d /sys/class/net/$IFNAME ] && {
-    (ip link set $IFNAME type bridge > /dev/null 2>&1) || (brctl addbr $IFNAME)
-    ip link set $IFNAME up
-}
-
-# If it's a bridge, we need to create a veth pair
-[ $IFTYPE = bridge ] && {
-    LOCAL_IFNAME=pl$NSPID$CONTAINER_IFNAME
-    GUEST_IFNAME=pg$NSPID$CONTAINER_IFNAME
-    ip link add name $LOCAL_IFNAME type veth peer name $GUEST_IFNAME
-    case "$BRTYPE" in
-        linux)
-            (ip link set $LOCAL_IFNAME master $IFNAME > /dev/null 2>&1) || (brctl addif $IFNAME $LOCAL_IFNAME)
-            ;;
-        openvswitch)
-            ovs-vsctl add-port $IFNAME $LOCAL_IFNAME
-            ;;
-    esac
-    ip link set $LOCAL_IFNAME up
-}
-
-# If it's a physical interface, create a macvlan subinterface
-[ $IFTYPE = phys ] && {
-    GUEST_IFNAME=ph$NSPID$CONTAINER_IFNAME
-    ip link add link $IFNAME dev $GUEST_IFNAME type macvlan mode bridge
-    ip link set $IFNAME up
-}
-
-ip link set $GUEST_IFNAME netns $NSPID
-ip netns exec $NSPID ip link set $GUEST_IFNAME name $CONTAINER_IFNAME
-
-# Setting macaddress
-if ! [ -z $MACADDR ];then
-    ip netns exec $NSPID ip link set $CONTAINER_IFNAME address $MACADDR
-fi
-
-if [ "$IPADDR" = "dhcp" ]
-then
-    ip netns exec $NSPID udhcpc -qi $CONTAINER_IFNAME
-else
-    ip netns exec $NSPID ip addr add $IPADDR dev $CONTAINER_IFNAME
-    [ "$GATEWAY" ] && {
-    ip netns exec $NSPID ip route delete default >/dev/null 2>&1 && true
-    }
-    ip netns exec $NSPID ip link set $CONTAINER_IFNAME up
-    [ "$GATEWAY" ] && {
-    ip netns exec $NSPID ip route replace default via $GATEWAY
-    }
-fi
-
-# Give our ARP neighbors a nudge about the new interface
-if which arping > /dev/null 2>&1
-then
-    IPADDR=$(echo $IPADDR | cut -d/ -f1) 
-    set +e
-    ip netns exec $NSPID arping -c 1 -A -I $CONTAINER_IFNAME $IPADDR > /dev/null 2>&1
-    set -e
-else
-    echo "${warn} : arping not found; interface may not be immediately reachable"
-fi
-
-    n=$((n + 1))
+    
+    if [ "$IPADDR" = "dhcp" ]
+    then
+        ip netns exec $NSPID udhcpc -qi $CONTAINER_IFNAME
+    else
+        ip netns exec $NSPID ip addr add $IPADDR dev $CONTAINER_IFNAME
+        [ "$GATEWAY" ] && {
+        ip netns exec $NSPID ip route delete default >/dev/null 2>&1 && true
+        }
+        ip netns exec $NSPID ip link set $CONTAINER_IFNAME up
+        [ "$GATEWAY" ] && {
+        ip netns exec $NSPID ip route replace default via $GATEWAY
+        }
+    fi
+    
+    # Give our ARP neighbors a nudge about the new interface
+    if which arping > /dev/null 2>&1
+    then
+        IPADDR=$(echo $IPADDR | cut -d/ -f1) 
+        set +e
+        ip netns exec $NSPID arping -c 1 -A -I $CONTAINER_IFNAME $IPADDR > /dev/null 2>&1
+        set -e
+    else
+        echo "${warn} : arping not found; interface may not be immediately reachable"
+    fi
+    
+        n=$((n + 1))
 done
 
 if [ -z "$ROUTEFILE" ] && [ -r /etc/docker/routes.cfg ]; then
